### ISSUE TITLE
Feature Request: Open link without marking it as read

### ISSUE THREAD

**Issue by rafaud** [chrisgrieser/alfred-read-later#5]
### Feature Requested

Right now there's no way of opening item without marking it as read. But in few situations it would be convenient to just open link without marking it as read (for example if you want to share it). Maybe just do it by holding `⌥ option` key. 

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
Good idea, added in 1.5.0

Available in the Alfred Gallery in 1-2 days, or directly by downloading the latest release here: https://github.com/chrisgrieser/alfred-read-later/releases/download/1.5.0/alfred-read-later.alfredworkflow
